export const CartActionTypes = {
  TOGGLE_CART: "TOGGLE_CART",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  DECREASE_QUANTITY: "DECREASE_QUANTITY",
  EMPTY_CART: "EMPTY_CART",
  EMPTY_CART_FAILURE: "EMPTY_CART_FAILURE"
};
