export const CartActionTypes = {
  TOGGLE_CART: "TOGGLE_CART",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  DECREASE_QUANTITY: "DECREASE_QUANTITY",
  EMPTY_CART: "EMPTY_CART",
  CART_FAILURE: "CART_FAILURE",
  SET_FIREBASE_CART_START: "SET_FIREBASE_CART_START",
  SET_FIREBASE_CART_SUCCESS: "SET_FIREBASE_CART_SUCCESS",
  UPDATE_FIREBASE_CART_START: "UPDATE_FIREBASE_CART_START",
  UPDATE_FIREBASE_CART_SUCCES: "UPDATE_FIREBASE_CART_SUCCES"
};
